src/main/java/com/artpie/composer/Repository.java
src/test/java/com/artpie/composer/RepositoryTest.java

Add Repository.add() method, which could be used to add packages to repository

#1 - Adding Package to Repository

---

pom.xml

#29 - Updated parent to 0.3 and ASTO to 0.14.1

---

README.md

#21 - Project status section added to README.md

---

pom.xml
src/main/java/com/artpie/composer/http/PackageMetadata.java
src/main/java/com/artpie/composer/http/PhpComposer.java
src/main/java/com/artpie/composer/http/Resource.java
src/main/java/com/artpie/composer/http/package-info.java
src/test/java/com/artpie/composer/http/PhpComposerTest.java
src/test/java/com/artpie/composer/http/package-info.java

Part of issue #24
Implementation skeleton for PHP Composer slice with placeholder PackageMetadata resource

#24 - PHP Composer slice skeleton with routing

---

src/main/java/com/artpie/composer/http/PackageMetadata.java
src/main/java/com/artpie/composer/http/PhpComposer.java
src/test/java/com/artpie/composer/http/PhpComposerTest.java

Part of issue #24 
Supporting GET requests to PackageMetadata which stream content from underlying Storage

#24 - Support for GET method of PackageMetadata resource

---

pom.xml
src/main/java/com/artpie/composer/http/PhpComposer.java
src/test/java/com/artpie/composer/http/PhpComposerTest.java

Closes issue #35
Migration to HTTP 0.5

#35 - Migrated to HTTP 0.5

---

src/main/java/com/artpie/composer/http/PackageMetadata.java
src/main/java/com/artpie/composer/http/PhpComposer.java
src/main/java/com/artpie/composer/http/Root.java
src/test/java/com/artpie/composer/http/PhpComposerTest.java

Part of issue #22 
Added routing to root path to support pushing a package to this path by PUT method.

#22 - Support for root resource routing

---

pom.xml
src/test/java/com/artpie/composer/JsonPackagesTest.java
src/test/java/com/artpie/composer/RepositoryTest.java
src/test/java/com/artpie/composer/http/PhpComposerTest.java

Closes issue #33  
Replaced FileStorage with InMemoryStorage in tests

#33 - Using InMemoryStorage in tests instead of FileStorage in tests

---

README.md
src/main/java/com/artipie/composer/JsonPackage.java
src/main/java/com/artipie/composer/JsonPackages.java
src/main/java/com/artipie/composer/Name.java
src/main/java/com/artipie/composer/Package.java
src/main/java/com/artipie/composer/Packages.java
src/main/java/com/artipie/composer/Repository.java
src/main/java/com/artipie/composer/http/PackageMetadata.java
src/main/java/com/artipie/composer/http/PhpComposer.java
src/main/java/com/artipie/composer/http/Resource.java
src/main/java/com/artipie/composer/http/Root.java
src/main/java/com/artipie/composer/http/package-info.java
src/main/java/com/artipie/composer/package-info.java
src/test/java/com/artipie/composer/JsonPackageTest.java
src/test/java/com/artipie/composer/JsonPackagesTest.java
src/test/java/com/artipie/composer/NameTest.java
src/test/java/com/artipie/composer/RepositoryTest.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java
src/test/java/com/artipie/composer/http/package-info.java
src/test/java/com/artipie/composer/package-info.java

#37 - com.artpie package renamed to com.artipie

---

.github/workflows/maven.yml
pom.xml
src/test/java/com/artipie/composer/RepositoryHttpIT.java
src/test/resources/log4j.properties

Part of issue #24 
Added disabled integration test to check that installation of packages via composer works. Issue will be complete when the test passes

#24 - Composer install integration test skeleton

---

src/main/java/com/artipie/composer/http/PackageMetadata.java
src/main/java/com/artipie/composer/http/PhpComposer.java
src/main/java/com/artipie/composer/http/Resource.java
src/main/java/com/artipie/composer/http/Root.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

Part of issue #22 
Adding package metadata by PUT method with JSON in body

#22 - Adding package via HTTP

---

pom.xml
src/main/java/com/artipie/composer/http/Root.java
src/test/java/com/artipie/composer/RepositoryHttpIT.java

Part of issue #24 
Now integration test for installation of package from repository is ready and can be used to implement full support in adapter.

#24 - Adding package to repository in package installation test

---

src/main/java/com/artipie/composer/Repository.java
src/test/java/com/artipie/composer/RepositoryAddTest.java

Part of issue #24 
Add package to repository also adds package to list of all packages

#24 - Repository.add() adds package to all all packages enumeration

---

src/main/java/com/artipie/composer/http/PackageMetadata.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

Part of #24 
Added route to `packages.json` by which all packages list may be retrieved.

#24 - Added route to all packages list

---

README.md
src/test/java/com/artipie/composer/RepositoryHttpIT.java

Closes issues #24 and #22 
Enabled integration test for installing and adding a package, updated project status in README.md

#24 - Installing and adding packages test enabled

---

pom.xml
src/main/java/com/artipie/composer/Repository.java
src/test/java/com/artipie/composer/RepositoryAddTest.java

Closes #48 
Removing source value in Repository.add() method

#48 - Cleaning up package after it has been added to repository

---

.github/workflows/maven.yml
pom.xml

#50 - Enabled code coverage reports, upgraded ppom to 0.3.3

---

pom.xml
src/main/java/com/artipie/composer/AllPackages.java
src/main/java/com/artipie/composer/JsonPackages.java
src/main/java/com/artipie/composer/Repository.java
src/main/java/com/artipie/composer/http/PackageMetadata.java
src/main/java/com/artipie/composer/http/Root.java
src/test/java/com/artipie/composer/JsonPackagesTest.java
src/test/java/com/artipie/composer/RepositoryAddTest.java
src/test/java/com/artipie/composer/RepositoryHttpIT.java
src/test/java/com/artipie/composer/RepositoryPackagesTest.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

#1 - Bumped dependencies

---

pom.xml
src/main/java/com/artipie/composer/http/PhpComposer.java
src/test/java/com/artipie/composer/RepositoryHttpIT.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

Closes #64 
Removed base path support

#64 - Removed base path support

---

src/test/java/com/artipie/composer/RepositoryHttpIT.java

Closes #69 
IT test fix, compatible with composer 2.0.8

#69 - IT test fix, compatible with composer 2.0.8

---

src/main/java/com/artipie/composer/Repository.java
src/main/java/com/artipie/composer/http/AddSlice.java
src/main/java/com/artipie/composer/http/PhpComposer.java
src/test/java/com/artipie/composer/RepositoryAddTest.java

Part of #67 
Adding package done without direct `Storage` access

#67 - Adding package done without direct Storage access

---

src/main/java/com/artipie/composer/JsonPackages.java
src/main/java/com/artipie/composer/Packages.java
src/main/java/com/artipie/composer/Repository.java
src/main/java/com/artipie/composer/http/PackageMetadataSlice.java
src/main/java/com/artipie/composer/http/PhpComposer.java
src/test/java/com/artipie/composer/RepositoryHttpIT.java
src/test/java/com/artipie/composer/RepositoryPackagesTest.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

Closes #67 
HTTP layer does not interact with Storage directly

#67 - HTTP layer does not interact with Storage directly

---

src/main/java/com/artipie/composer/AstoRepository.java
src/main/java/com/artipie/composer/Repository.java
src/test/java/com/artipie/composer/AstoRepositoryAddTest.java
src/test/java/com/artipie/composer/AstoRepositoryPackagesTest.java
src/test/java/com/artipie/composer/RepositoryHttpIT.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

Closes #75 
Repository interface extracted

#75 - Repository interface extracted

---

pom.xml
src/test/java/com/artipie/composer/RepositoryHttpIT.java

Closes #78 
Used Testcontainers for IT cases.
Updated `com.artipie.http` from `0.16.1` to `0.17.7` to use `RandomFreePort`.

#78 - Use Testcontainers for IT

---

src/main/java/com/artipie/composer/http/PhpComposer.java
src/test/java/com/artipie/composer/http/RepositoryHttpIT.java
src/test/java/com/artipie/composer/test/ComposerSimple.java
src/test/java/com/artipie/composer/test/HttpUrlUpload.java
src/test/java/com/artipie/composer/test/PackageSimple.java
src/test/java/com/artipie/composer/test/TestAuthentication.java
src/test/java/com/artipie/composer/test/package-info.java

Part of #71 
Used `BasicAuthSlice`, extracted test classes

#71 - Use BasicAuthSlice, extract test classes

---

src/test/java/com/artipie/composer/http/RepositoryHttpAuthIT.java

Closes #71 
Added auth IT for repository HTTP

#71 - Add auth IT for repository HTTP

---

src/main/java/com/artipie/composer/AstoRepository.java
src/main/java/com/artipie/composer/JsonPackage.java
src/main/java/com/artipie/composer/JsonPackages.java
src/main/java/com/artipie/composer/Packages.java
src/main/java/com/artipie/composer/http/PackageMetadataSlice.java
src/main/java/com/artipie/composer/misc/ContentAsJson.java
src/main/java/com/artipie/composer/misc/package-info.java
src/test/java/com/artipie/composer/AstoRepositoryAddTest.java
src/test/java/com/artipie/composer/AstoRepositoryPackagesTest.java
src/test/java/com/artipie/composer/JsonPackageTest.java
src/test/java/com/artipie/composer/JsonPackagesTest.java
src/test/java/com/artipie/composer/http/PhpComposerTest.java

Closes #85 
Replaced `ByteSource` with `Content`

#85 - Use Content instead of ByteSource

---

pom.xml
src/main/java/com/artipie/composer/http/CachedProxySlice.java
src/main/java/com/artipie/composer/http/ComposerProxySlice.java
src/test/java/com/artipie/composer/http/CachedProxySliceTest.java

Part of #77 
Added skeleton for proxy implementation. I suppose to cache files from remote repository

#77 - Add skeleton for proxy implementation

---

src/main/java/com/artipie/composer/http/CachedProxySlice.java
src/test/java/com/artipie/composer/http/CachedProxySliceTest.java

Part of #77 
Added unit tests for `CachedProxySlice` for different scenarios

#77 - Add unit tests for CachedProxySlice

---

src/main/java/com/artipie/composer/AstoRepository.java
src/main/java/com/artipie/composer/JsonPackage.java
src/main/java/com/artipie/composer/JsonPackages.java
src/main/java/com/artipie/composer/http/AddSlice.java
src/main/java/com/artipie/composer/http/proxy/MergePackage.java
src/test/java/com/artipie/composer/AstoRepositoryAddJsonTest.java
src/test/java/com/artipie/composer/http/ArchiveZipTest.java
src/test/java/com/artipie/composer/http/RepositoryHttpAuthIT.java
src/test/java/com/artipie/composer/http/RepositoryHttpIT.java
src/test/java/com/artipie/composer/test/EmptyZip.java
src/test/java/com/artipie/composer/test/PackageSimple.java
src/test/resources-binary/package-without-version.json

Closes #83
Added unit tests, IT for package without version.
Also, extracted repeated method for creating empty ZIP.

Added unit tests, IT for package without version

---

src/main/java/com/artipie/composer/http/proxy/MergePackage.java
src/test/java/com/artipie/composer/http/proxy/EmptyAllPackagesSliceTest.java
src/test/java/com/artipie/composer/http/proxy/MergePackageWithRemoteTest.java
src/test/resources-binary/merge/local.json
src/test/resources-binary/merge/remote.json

Part of #77 
Added unit tests for merging parts of local index and the remote one.
Also added test for `EmptyAllPackagesSlice`.

Added unit tests for merging parts of indexes

---

src/test/java/com/artipie/composer/http/RepositoryHttpAuthIT.java
src/test/java/com/artipie/composer/http/RepositoryHttpIT.java
src/test/java/com/artipie/composer/test/PackageSimple.java
src/test/java/com/artipie/composer/test/SourceServer.java

Closes #102 
Extracted `SourceServer` class to avoid code duplicating

Extract SourceServer class

---

src/test/java/com/artipie/composer/http/HttpZipArchiveIT.java
src/test/java/com/artipie/composer/http/RepositoryHttpAuthIT.java
src/test/java/com/artipie/composer/http/RepositoryHttpIT.java
src/test/java/com/artipie/composer/http/proxy/ComposerProxySliceIT.java
src/test/java/com/artipie/composer/test/PackageSimple.java

Part of #77 
Added IT for installation from local for remote repository.
Also, moved creation of instance `Vertx` to avoid creating for per method.

Add IT for installation from local for remote

---

src/main/java/com/artipie/composer/AstoRepository.java
src/main/java/com/artipie/composer/Repository.java
src/main/java/com/artipie/composer/http/proxy/CacheTimeControl.java
src/test/java/com/artipie/composer/http/proxy/CacheTimeControlTest.java

Part of #77 
Added  `CacheTimeControl` and tests for it. Read values from `cache/cache-info.json` and check expiration

Add `CacheTimeControl` and tests for it

---

src/main/java/com/artipie/composer/http/proxy/ComposerStorageCache.java
src/test/java/com/artipie/composer/http/proxy/ComposerStorageCacheTest.java

Part of #77 
Added unit tests for `ComposerStorageCache`. Fixed a bit implementation of this class

Added unit tests for `ComposerStorageCache`

---

src/main/java/com/artipie/composer/http/proxy/ComposerStorageCache.java
src/test/java/com/artipie/composer/http/HttpZipArchiveIT.java
src/test/java/com/artipie/composer/http/RepositoryHttpAuthIT.java
src/test/java/com/artipie/composer/http/RepositoryHttpIT.java
src/test/java/com/artipie/composer/http/proxy/CacheComposerIT.java
src/test/java/com/artipie/composer/http/proxy/ComposerProxySliceIT.java

Closes #77 
Added IT case for installation from cache. Made class `ComposerStorageCache` public for using in `artipie` module

Add IT for installation from cache

---

.rultor.yml

Add myself to `rultor.yml` to get permission to release

Add to rultor
